packages:
  - packages/*
  - apps/*

ignoredBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - nx
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - lefthook
