#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

pnpm exec validate-branch-name -r "^(master|main|develop){1}$|^(feature|fix|hotfix|release|renovate)/.+$"
pnpm run check-lock-files
pnpm exec lint-staged --concurrent false
pnpm exec nx affected:test
